workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.diyar"
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.example.diyar
    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Install CocoaPods
        script: find . -name "Podfile" -execdir pod install \;

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - dogethertech@gmail.com
        notify:
          success: true
          failure: true
