workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.dogethertech.diyar
    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Build iOS IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - dogethertech@gmail.com
        notify:
          success: true
          failure: true
